### ISSUE TITLE
StartCommand : Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by JuGid** [certificationy/certificationy-cli#59]
Hi,

I wanted to try your training app. Using composer, I just ran the commands and start it.

This is more information about my environment : 

```
PHP 7.4.16 (cli) (built: Mar  4 2021 20:52:51) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
```

Also, this is the stack trace : 

```
MacBook-Pro-de-Julien:certificationy-cli juliengidel$ php certificationy.php start --number=3
PHP Warning:  file_get_contents(): Filename cannot be empty in /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php on line 63

Warning: file_get_contents(): Filename cannot be empty in /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php on line 63
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Certificationy\Loaders\YamlLoader::__construct() must be of the type array, null given, called in /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php on line 66 and defined in /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/certificationy/certificationy/src/Loaders/YamlLoader.php:35
Stack trace:
#0 /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php(66): Certificationy\Loaders\YamlLoader->__construct(NULL)
#1 /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/symfony/console/Command/Command.php(299): Certificationy\Cli\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInpu in /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/certificationy/certificationy/src/Loaders/YamlLoader.php on line 35

Fatal error: Uncaught TypeError: Argument 1 passed to Certificationy\Loaders\YamlLoader::__construct() must be of the type array, null given, called in /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php on line 66 and defined in /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/certificationy/certificationy/src/Loaders/YamlLoader.php:35
Stack trace:
#0 /Users/juliengidel/Documents/Programmation/certificationy-cli/src/Command/StartCommand.php(66): Certificationy\Loaders\YamlLoader->__construct(NULL)
#1 /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/symfony/console/Command/Command.php(299): Certificationy\Cli\Command\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInpu in /Users/juliengidel/Documents/Programmation/certificationy-cli/vendor/certificationy/certificationy/src/Loaders/YamlLoader.php on line 35
```

I solved the issue by using this path function in StartCommand.php : 

```
protected function path(string $config = null): string
{
      $defaultConfig = dirname(__DIR__) . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'config.yml';

      return file_exists($config) ? $config : $defaultConfig;
}
```

and modified start command beginning : 

```
protected function execute(InputInterface $input, OutputInterface $output): int
{
        $config = $this->path($input->getOption('config'));
        ...
}
```

The problem is that the code doesn't test if the file exists and it's not sure that the string file path is not empty.

Sorry for not making a PR for that, I don't really have much time to and hope you'll excuse me.
If this is not a so blocking issue, I will be able to do one mid-week in answer to this issue.

Bye ! 😄

**Comment by tienvx** [comment]
Here is the merge request: #61

**Comment by mickaelandrieu** [comment]
Release done, please upgrade and enjoy !
